### ISSUE TITLE
With Hoptoad installed you get no error logging in development

### ISSUE THREAD

**Issue by betelgeuse** [mperham/girl_friday#11]
```
  8     def self.default
  9       defined?(HoptoadNotifier) ? Hoptoad : self
 10     end
```

In development Hoptoad doesn't send exceptions anywhere. This means that if you have the hoptoad gem in your Gemfile then girl_friday doesn't show development exceptions anywhere either.

**Comment by mperham** [comment]
In your Gemfile:

```
group :production do
  gem 'hoptoad_notifier'
end
```

**Comment by betelgeuse** [comment]
Yes it's possible to work around it. Your solution alone isn't enough though if you use the default Hoptoad initializer as it can't find HoptoadNotifier. I think behavior should at least be documented if it's expected that people configure hoptoad in some other way than the hoptoad generator does.

**Comment by mperham** [comment]
I still have no idea what to do here.  Either I pull the automatic Hoptoad support and force the user to explicitly activate Hoptoad or I build in a notion of environment, neither of which I really want to do.  Opinions welcome.

**Comment by betelgeuse** [comment]
I think either of the options you listed is better than the current situation.

**Comment by betelgeuse** [comment]
For the notion of env doesn't RACK_ENV cut it?

**Comment by intjonathan** [comment]
There's always the multiple backend option like Resque. Just stack error handlers and call them all.
