### ISSUE TITLE
pipeline.rb - which image library is required?

### ISSUE THREAD

**Issue by drnic** [mperham/girl_friday#24]
I'm running OS X 10.7. When I run the pipeline.rb example I am told it cannot load libclparser.dylib from OpenCL.framework. How do I this? (perhaps put this at the top of the pipeline.rb file?)

```
$ ruby examples/pipeline.rb 
#<Thread:0x617e53c9>: Pushing http://blog.carbonfive.com
#<Thread:0x17773a14>: Fetching image: http://blog.carbonfive.com/wp-content/uploads/2011/08/carbonite-1.png
#<Thread:0x132fae6c>: Fetching image: http://blog.carbonfive.com/wp-includes/images/rss.png
dyld: Library not loaded: /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libclparser.dylib
  Referenced from: /usr/local/bin/identify
  Reason: image not found
#<Thread:0x17773a14>: Image: 

# hangs here
```

**Comment by jc00ke** [comment]
Can you run `identify` from the terminal on an image & get reasonable output? Might be an imagemagick thing.

**Comment by mperham** [comment]
I believe that's because you migrated your Snow Leopard system with an existing ImageMagick install.  You need to reinstall ImageMagick with brew so it is recompiled.

**Comment by drnic** [comment]
`brew install ImageMagick` worked; thanks guys.
