### ISSUE TITLE
no such file to load -- sinatra/base (LoadError)

### ISSUE THREAD

**Issue by fbjork** [mperham/girl_friday#26]
I added the following to my config.ru file:

require 'girl_friday/server'

run Rack::URLMap.new "/" => TestApp::Application, "/girl_friday" => GirlFriday::Server.new

when I start my app I get the following error:

/Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require': no such file to load -- sinatra/base (LoadError)
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in`block in require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in`require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/girl_friday-0.9.4/lib/girl_friday/server.rb:1:in `<top (required)>'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in`require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in`block in load_dependency'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /Users/fredrik/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
    from /Users/fredrik/Projects/test-app/config.ru:2:in`block in <main>'

**Comment by fbjork** [comment]
Looks like sinatra is only a development dependency when I check the .gemspec, guess that is the issue?

**Comment by mperham** [comment]
Sinatra is meant to be an optional dependency so you don't have to have Sinatra add extra bulk to your application gemset if you don't want the UI.  Just add sinatra to your gemfile.

**Comment by fbjork** [comment]
Got it, thanks!
