### ISSUE TITLE
Add timeout to GirlFriday::Batch

### ISSUE THREAD

**Issue by fbjork** [mperham/girl_friday#28]
Would be great to see support for timeout in GirlFriday::Batch. Right now I'm doing this: https://gist.github.com/1223340 which seems like an ugly hack.

**Comment by mperham** [comment]
Turns out it already exists, I'm that good.

```
Batch#results(timeout=nil)
```

**Comment by fbjork** [comment]
Ok nice!

I tried this:

batch = GirlFriday::Batch.new(friends, size: 3 do |friend|
  # do work
end

updates = batch.results(1)

but the method takes several seconds to complete anyway. Is this the right syntax?

**Comment by mperham** [comment]
That's correct.  I don't have a test for batch timeout - I will add
one right now.

On Mon, Sep 19, 2011 at 1:29 PM, Fredrik Björk
reply@reply.github.com
wrote:

> I tried this:
> 
> batch = GirlFriday::Batch.new(friends, size: 3 do |friend|
>  # do work
> end
> 
> updates = batch.results(1)
> 
> but the method takes several seconds to complete anyway. Is this the right syntax?
