### ISSUE TITLE
Threads not being killed when using GirlFriday::Batch

### ISSUE THREAD

**Issue by fbjork** [mperham/girl_friday#30]
I've created a repo where this can be reproduced here:
https://github.com/fbjork/girl-friday-batch-example

run unicorn and point the browser to http://localhost:8080, then open Activity Monitor and watch the Thread column increase everytime you refresh the browser without decreasing.

**Comment by mperham** [comment]
Thanks, I've tracked down the issue (the actor threads are never actually exiting so they are never GC'd) and have a fix in testing.  I expect this to make things a little more stable for you on Heroku.  :-)

**Comment by fbjork** [comment]
Nice one. Thanks for fixing!

**Comment by fbjork** [comment]
Could this also be why the timeout isn't working for me in Batch?

**Comment by mperham** [comment]
This issue uncovered this Ruby bug:

http://redmine.ruby-lang.org/issues/5342

**Comment by fbjork** [comment]
Can it be fixed without waiting for Ruby 1.9.3?

**Comment by stevenh512** [comment]
Maybe try monkey-patching Ruby's thread class until the fix is backported? I think something like this should work:

https://gist.github.com/1229959

**Comment by mperham** [comment]
It doesn't block the fix, just prevented the tests from working until I found a workaround. More tomorrow.

**Comment by fbjork** [comment]
Sweet! These commits should fix Threads not being killed and timeout not working in Batch, correct?

**Comment by mperham** [comment]
Yes, and should dramatically improve how well GF works on Heroku.  Let
me know how it goes.

On Wed, Sep 21, 2011 at 5:02 PM, Fredrik Björk
reply@reply.github.com
wrote:

> Sweet! These commits should fix Threads not being killed and timeout not working in Batch, correct?
