### ISSUE TITLE
Instructions for use on Heroku

### ISSUE THREAD

**Issue by antunderwood** [mperham/girl_friday#31]
On the main page for Girl Friday (http://mperham.github.com/girl_friday/)  it mentions that for info on how to use Girl Friday on Heroku to the look on the github wiki pages. After quite a thorough search on the github wiki I can't find any reference to Heroku. Please could you point me in the right direction.

Thanks, Anthony

**Comment by jc00ke** [comment]
Hey Anthony,
I added a tiny blurb at the end of the FAQ: https://github.com/mperham/girl_friday/wiki/FAQ

It's not Heroku specific, it's just that since Heroku uses 1.9.2, you would need to run Unicorn or Rainbows!. It was inferred but that wasn't good enough. Hope the little addition is enough to clear up any confusion.

**Comment by antunderwood** [comment]
Thanks for the reply. I have a small test app using Unicorn and running on a Cedar stack on Heroku

Procfile
```web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb

``````
config/unicorn.rb
```worker_processes 3 # amount of unicorn workers to spin up
timeout 30         # restarts workers that hang for 30 seconds
``````

Since I have 3 workers does this mean it would not be sensible to use more than 2 works for girl_friday via :size=>2???

Thanks Anthony

**Comment by jc00ke** [comment]
There have been rumors that Heroku supports up to 15 threads per process, so that means you could have up to 45 threads with which to use for workers. We would love to find the exact number. I would bet it's more like 5-10.

**Comment by antunderwood** [comment]
sorry for being slow... So if I have specified 3 worker_processes for unicorn this would mean (based on 5-10) 15-130 threads.
If I specify :size => 5 for a girl_friday queue is this referring to threads or workers.

In the Readme its states ":size is the number of workers to spin up and defaults to 5." so I assumed that I could not specify any more than the number of workers in the unicorn config file.

**Comment by jc00ke** [comment]
No worries, it's confusing since both GF & Unicorn talk about workers. You are correct: if you specify

``` ruby
:size => 5
```

then GF will use 5 threads, but you may have more threads available through the number or Unicorn workers you specified.

**Comment by antunderwood** [comment]
OK. I understand now. Thanks for your quick and comprehensive replies. Now to try it out :)

**Comment by ckbhodge** [comment]
For anyone else who tries to get unicorn running with girl_friday on heroku, I hit a few issues and I wanted to share the solution.

The first was I got a redirecting error without including "preload_app true" in the unicorn config file.  

The second was an ActiveRecord error that showed up in the logs: "activerecord::statementinvalid - pgerror: ssl error: decryption failed or bad record mac".

The final solution was to change my unicorn.rb config file to this:

worker_processes 4 # amount of unicorn workers to spin up
timeout 30         # restarts workers that hang for 30 seconds
preload_app true

# What to do before we fork a worker

before_fork do |server, worker|
 ActiveRecord::Base.connection_handler.clear_all_connections!
end

# What to do after we fork a worker

after_fork do |server, worker|
 ActiveRecord::Base.connection_handler.verify_active_connections!
end

I hope this helps!

**Comment by bruno-** [comment]
I had issues with girl_friday on heroku and I found the solution here: https://github.com/mperham/girl_friday/issues/47
