### ISSUE TITLE
Intermittently failing batch test

### ISSUE THREAD

**Issue by jc00ke** [mperham/girl_friday#34]
`test_simple_batch_operation` fails some of the time on all impls. 

```
∴ rake
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
Loaded suite /home/jesse/.rvm/gems/ruby-1.9.2-p290@global/gems/rake-0.9.2/lib/rake/rake_test_loader
Started
...F.............
Finished in 0.645033 seconds.

  1) Failure:
test_simple_batch_operation(TestBatch) [/home/jesse/projects/girl_friday/test/test_batch.rb:19]:
Expected 0.5 - 0.0112529 (0.4887471) to be < 0.1.

17 tests, 37 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by jc00ke** [comment]
Just happened on Travis. See [Build 67.1](http://travis-ci.org/#!/mperham/girl_friday/builds/184275)

**Comment by mperham** [comment]
I'll look into this when I have some time, probably at Rubyconf.

**Comment by jc00ke** [comment]
Cool, see ya there.

**Comment by ryanlecompte** [comment]
Ah good, this is the same error I am seeing on Travis right after my last merge to master. Glad it wasn't directly linked to my last change.

Wish I were going to Rubyconf and could meet you guys! I'll be in SF until Oct. 12th, though.

**Comment by jc00ke** [comment]
@mperham Did this ever get resolved?

**Comment by mperham** [comment]
I have no idea.  1.9.2 never fails on my machine but still seems to be broken on Travis.

**Comment by xaviershay** [comment]
This is still a thing, see recent failed builds: http://travis-ci.org/#!/mperham/girl_friday/builds
