### ISSUE TITLE
girl_friday integration with mod rails (passenger)

### ISSUE THREAD

**Issue by matthewpurdy** [mperham/girl_friday#38]
girl_friday works with mod rails (passenger) version 3.0.9; however to make it work you must change the spawn method to conservative (note: same thing with eventmachine) in the /etc/httpd/conf.d/myproject.conf

PassengerSpawnMethod conservative

this is not a bug; however, it would be nice to have this documented for the next guy :-)

**Comment by mperham** [comment]
Thanks for the note, Matthew.  I believe if you create your queues lazily, rather than in config/initializers, you shouldn't need conservative spawning.

**Comment by matthewpurdy** [comment]
how do you create the queue lazily?  where would i put them in the rails app so they wouldnt go out of scope?

i created my queue in config/initializers/girl_friday.rb

  #initialize queue
  PACKAGING_QUEUE = GirlFriday::WorkQueue.new(:packager) do |msg|
    PackageLogic.package_by_hash(msg)
  end

in my controller i use:

```
#create the parameter_hash from a subset of params
PACKAGING_QUEUE << parameter_hash
redirect_to :back
```

i am running rails 3.0.10 on ruby 1.9.2-p290 on centos 5.7 with passenger 3.0.9
my gems that i am using in my app are:
gem 'rails',        '3.0.10'
gem 'open4',        '1.2.0'
gem 'rake',         '0.9.2'
#gem 'eventmachine', '0.12.10'
gem 'girl_friday',  '0.9.6'
gem 'mysql2',       '0.2.13'

note: when i switch out girl_friday with eventmachine; i get the same results (i.e. both do not work with smart spawning). i assume you have to create the event machine server lazily also.
note2: i do use open4 in my library which is what the job engine runs
