### ISSUE TITLE
no such file to load -- girl_friday/server (LoadError)

### ISSUE THREAD

**Issue by mrrooijen** [mperham/girl_friday#4]
```
require ::File.expand_path('../config/environment',  __FILE__)
require 'girl_friday/server'

run Rack::URLMap.new \
  "/"            => Gfapp::Application,
  "/girl_friday" => GirlFriday::Server.new
```

Seems it can't find the Sinatra app, which is odd because the path should be correct, looking at the gem structure and the lib being in the load path.

**Comment by mperham** [comment]
The server bits haven't been released in a gem yet.

On Sun, May 1, 2011 at 6:31 PM, meskyanichi
reply@reply.github.com
wrote:

**Comment by mrrooijen** [comment]
Ah, gotcha!

---

Michael van Rooijen
https://github.com/meskyanichi
http://twitter.com/#!/meskyanichi

On Monday, May 2, 2011 at 5:37 PM, mperham wrote:
The server bits haven't been released in a gem yet.

**Comment by mperham** [comment]
Should be fixed with latest release.
