### ISSUE TITLE
Use Celluloid for actors

### ISSUE THREAD

**Issue by grantr** [mperham/girl_friday#50]
Not an issue, more of a question. [Sidekiq](/mperham/sidekiq) uses [celluloid](/celluloid/celluloid) for actors, so maybe girl_friday should too?

**Comment by mperham** [comment]
Doubtful.  girl_friday has reached a level of stability - no sense in tearing it apart for no end-user-visible reason.  Also, notice the celluloid branch?

**Comment by grantr** [comment]
Fair enough. Didn't see the celluloid branch, thanks for the pointer!

**Comment by tarcieri** [comment]
Seems like Sidekiq is already girl_friday rebuilt on top of Celluloid ;)

**Comment by mperham** [comment]
With one vital difference: girl_friday is in-process.  Sidekiq is standalone.

**Comment by grantr** [comment]
Sidekiq doesn't support in-process queues (that I know of), would be a nice addition though... :)
