### ISSUE TITLE
Specs fail on Gentoo

### ISSUE THREAD

**Issue by jc00ke** [mperham/girl_friday#52]
In trying to figure out why GF wasn't processing on EY I noticed the specs fail to run on Gentoo. I'll try to get this sorted out, since I use EY and they use Gentoo.

**Comment by mperham** [comment]
Do you know if they run on other Linux flavors?

**Comment by jc00ke** [comment]
Only Gentoo asaik.

**Comment by bernd** [comment]
Tested with MRI 1.9.3 and JRuby 1.6.7 on Ubuntu 10.04. No failures.

**Comment by xaviershay** [comment]
@jc00ke is this still a thing?
