### ISSUE TITLE
Rails 3 with girl_friday server

### ISSUE THREAD

**Issue by gaiottino** [mperham/girl_friday#53]
In the wiki you say that we can add the server to a Rails  3 app by adding stuff to config.ru. Any reason why you don't recomment mounting if in routes.rb? Feels alot cleaner. Here's how I mount it in a Rails 3 app using routes.rb

```
  require 'girl_friday/server'
  mount GirlFriday::Server, at: '/girl_friday'
```

**Comment by mperham** [comment]
I guess because that only works for Rails.  The config.ru change works for any Rack framework.  I think it's reasonable for you to update the wiki if you'd like to.
