### ISSUE TITLE
Repeating Tasks

### ISSUE THREAD

**Issue by andyl** [mperham/girl_friday#6]
I have a sinatra app and would like to create a simple in-process monitor that runs in a repeating task:

```
while true
  sleep 1000
  check_something_and_send_an_alert_if_it_fails
end
```

Is girl_friday a good solution for persistent/repeating tasks like this?  
Is there any example code that shows the best way to do repeating tasks with girl_friday?

tx, Andy

**Comment by mperham** [comment]
girl_friday has no support for scheduled tasks currently.  It's on my radar as a possible future feature but not something that can be gracefully handled today.  Integrating something like rufus-scheduler is possible.
