### ISSUE TITLE
Rubinius to drop actor.rb in favor of rubinius-actor gem 

### ISSUE THREAD

**Issue by barttenbrinke** [mperham/girl_friday#61]
I also filed the nameclash issue with rubinius and they have decided that they will drop the actor.rb and use the rubinius-actor gem instead: https://github.com/rubinius/rubinius/issues/1869 

So you guys will have to move the code around a bit..

**Comment by jc00ke** [comment]
I noted in the commit message that JRuby 1.7.0 failed for me but JRuby 1.6.8 still passes (see [travis run](https://travis-ci.org/#!/mperham/girl_friday/jobs/3087516)). I'll attempt to figure out what's up with 1.7.0 but probably refer to @headius.

**Comment by barttenbrinke** [comment]
Thanks! One less monkey patch to worry about :)

**Comment by mperham** [comment]
Unfortunately there's no way to optionally pull in the rubinius-actor gem for specific platforms in the gemspec afaik.  Is this possible?  The Gemfile makes no difference for the shipped gem.

**Comment by jc00ke** [comment]
`rubinius-actor` will install on `1.9.3` but will throw a `RuntimeError` when required.

```
22:51:19 jesse@chino:~  ruby-1.9.3-p286 
∴ irb
>> require 'rubinius/actor'
RuntimeError: Only supported on JRuby and Rubinius
```

I've committed changes that should take care of it: e927d9e
