### ISSUE TITLE
Using GF for periodic tasks on Heroku

### ISSUE THREAD

**Issue by bruno-** [mperham/girl_friday#62]
Would it be possible to use girl_friday for handling periodic tasks on heroku (or anywhere else)?

I have a small and simple task to do every hour. The task is written below.

```
class TaskQueue < GirlFriday::WorkQueue
  include Singleton
  def initialize
    super(:task_queue, size: 1) do
      loop {
        Task.to_do
        sleep 3600
      }
    end 
  end 

  def self.push *args
    instance.push *args
  end 

end
```

I've tried to make a rails initializer that would start the task above: `TaskQueue.push(nil)`
This does not seem to work as expected on my machine locally.

Is there a way to accomplish this idea somehow? 
Reason for this would be simplicity: not having to deal with cron or setting up (paid) heroku scheduler addon. Can't think of any drawbacks.
Thanks for help!

**Comment by jc00ke** [comment]
The best way to handle this kind of situation is to use cron or another scheduler like [Clockwork](https://github.com/tomykaira/clockwork).
