### ISSUE TITLE
Actor class in global scope?

### ISSUE THREAD

**Issue by rreusser** [mperham/girl_friday#71]
Am I correct in understanding that this gem places the 'Actor' class in the global scope? After installing Airbrake (which pulls in girl_friday), our Rails app now fails because 'Actor' has already been defined. Any suggestions for a straightforward solution that doesn't involve s/actor/aktor/?

**Comment by rreusser** [comment]
Current solution: s/Airbrake/Exceptional/

**Comment by mperham** [comment]
Yes, known issue on MRI.  I recommend new users to use sucker_punch because of this and a few other fundamental design mistakes I made in this gem.

The latest versions of airbrake do not require girl_friday anymore.

**Comment by rreusser** [comment]
Just checking. Thanks! And thanks for the airbrake tip!

**Comment by rreusser** [comment]
Also: Very sorry for my failure to check the closed issues list before asking!
